#!/bin/bash

# Go to the root directory.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd $DIR

# PIDFILE
PIDFILE="data/dbpid"

# Colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

# Columns
col=80

echo -n "Stopping OpenJUB Database: "

if [ ! -f $PIDFILE ]
then
  echo "Not running. "
  printf '%s%*s%s' "$RED" $col "[FAIL]" "$NORMAL"
  echo ""
  exit 1
fi

PID=$(cat $PIDFILE)

kill $PID
echo "Killed $PID"
rm $PIDFILE

printf '%s%*s%s' "$GREEN" $col "[OK]" "$NORMAL"
echo ""
